# Generated by Django 6.0.6 on 2026-08-07 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_records',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID univoco generato automaticamente (UUID4)', primary_key=True, serialize=False)),
                ('iva', models.CharField(max_length=11)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HR_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machinery_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID univoco generato automaticamente (UUID4)', primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('date_open', models.DateTimeField(verbose_name='date opened')),
                ('date_close', models.DateTimeField(verbose_name='date closed')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('OP', 'Open'), ('CL', 'Closed')], default='DR', max_length=2)),
                ('customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer_records')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="operation's date")),
                ('desc', models.CharField(max_length=500)),
                ('technician_fk', models.ManyToManyField(to='api.hr_records')),
                ('report_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='UsedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='qta')),
                ('inventory_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
                ('operation_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.operation')),
            ],
        ),
    ]
