# Generated by Django 6.0.5 on 2026-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_report_technicians_operation_technician_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='desc',
            field=models.CharField(default='report', max_length=100),
            preserve_default=False,
        ),
    ]
