# Generated by Django 6.0.5 on 2026-05-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='element',
            new_name='inv_masterdata_id',
        ),
    ]
