# Generated by Django 6.0.5 on 2026-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_inv_masterdata_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_masterdata',
            name='weight',
        ),
        migrations.AddField(
            model_name='inv_masterdata',
            name='measure_value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='measure_value'),
        ),
    ]
