# Generated by Django 6.0.5 on 2026-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_inv_masterdata_measure_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_masterdata',
            name='measure_value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='measure_value'),
        ),
    ]
