# Generated by Django 6.0.5 on 2026-05-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_inv_masterdata_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_masterdata',
            name='weight',
        ),
    ]
