# Generated by Django 6.0.5 on 2026-05-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_inv_masterdata_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='qta')),
                ('inventory_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.inventory')),
                ('operation_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.operation')),
            ],
        ),
    ]
