# Generated by Django 6.0.5 on 2026-05-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_inv_masterdata_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_masterdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.inv_masterdata', unique=True),
        ),
    ]
