# Generated by Django 6.0.5 on 2026-05-22 21:20

import django.db.models.deletion
import test1.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_records',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID univoco generato automaticamente (UUID4)', primary_key=True, serialize=False)),
                ('iva', models.CharField(max_length=11)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HR_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inv_masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('barcode', test1.models.EAN13Field(max_length=13, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('measure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Measure')),
            ],
        ),
        migrations.CreateModel(
            name='Machinery_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('is_decimal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.inv_masterdata')),
            ],
        ),
        migrations.AddField(
            model_name='inv_masterdata',
            name='measureUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.measureunit'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID univoco generato automaticamente (UUID4)', primary_key=True, serialize=False)),
                ('date_open', models.DateTimeField(verbose_name='date opened')),
                ('date_close', models.DateTimeField(verbose_name='date closed')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('OP', 'Open'), ('CL', 'Closed')], default='DR', max_length=2)),
                ('customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.customer_records')),
                ('technicians', models.ManyToManyField(to='test1.hr_records')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="operation's date")),
                ('desc', models.CharField(max_length=500)),
                ('report_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.report')),
            ],
        ),
    ]
