# Generated by Django 6.0.5 on 2026-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='technicians',
        ),
        migrations.AddField(
            model_name='operation',
            name='technician_fk',
            field=models.ManyToManyField(to='test1.hr_records'),
        ),
    ]
