# Generated by Django 6.0.5 on 2026-05-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_rename_element_inventory_inv_masterdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='inv_masterdata_id',
            new_name='inv_masterdata',
        ),
    ]
