# Generated by Django 6.0.5 on 2026-05-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_rename_inv_masterdata_id_inventory_inv_masterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_masterdata',
            name='measure',
        ),
    ]
