# Generated by Django 6.0.5 on 2026-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_alter_inventory_inv_masterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_masterdata',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight'),
            preserve_default=False,
        ),
    ]
