# Generated by Django 6.0.5 on 2026-05-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_remove_inv_masterdata_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_masterdata',
            name='measure_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='measure_value'),
        ),
    ]
