# Generated by Django 6.0.5 on 2026-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_alter_inv_masterdata_measure_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_masterdata',
            name='measure_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='measure_value'),
        ),
    ]
