# Generated by Django 6.0.6 on 2026-08-07 14:39

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inv_masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('barcode', inventory.models.EAN13Field(max_length=13, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('measure_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='measure_value')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('is_decimal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('inv_masterdata', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.inv_masterdata')),
            ],
        ),
        migrations.AddField(
            model_name='inv_masterdata',
            name='measureUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.measureunit'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
            ],
        ),
    ]
