# Generated by Django 6.1 on 2026-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='operation_direction',
            field=models.CharField(choices=[('IN', 'Inbound'), ('OU', 'Outbound')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
