# Generated by Django 6.1 on 2026-09-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movement_operation_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'permissions': [('can_adjust_movement', 'Can create a correction movement')]},
        ),
        migrations.AddField(
            model_name='movement',
            name='correction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.movement'),
        ),
        migrations.AddField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='created_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
