# Generated by Django 6.1 on 2026-10-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_customer_records_iva'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='customer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.customer_records'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_close',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date closed'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_open',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date opened'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('OP', 'Open'), ('CL', 'Closed'), ('CA', 'Cancelled'), ('HO', 'Hold on'), ('RU', 'Running'), ('PL', 'Planned'), ('PE', 'Pending')], default='DR', max_length=2),
        ),
    ]
