# Generated by Django 6.1 on 2026-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_records',
            name='iva',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
